{% set name = "vega-lite-cli" %}
{% set version = "5.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: true  # [nodejs == 14]

requirements:
  host:
    - nodejs
    - yarn
  run:
    - nodejs
    - vega-cli

test:
  commands:
    - curl -L https://github.com/vega/vega-lite/raw/v{{ version }}/examples/specs/bar.vl.json > test.json
    - vl2svg test.json > test.svg

about:
  home: https://vega.github.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Command line interface of the VEGA-lite visualization grammar'
  description: |
    The vega-lite-cli package includes four node.js-based command line utilities -
    vl2pdf, vl2png, vl2svg, and vl2vg - for rendering static visualization images.
    These commands render to PDF, PNG, SVG files, or plain VEGA, respectively.
  doc_url: https://vega.github.io/vega-lite/usage/compile.html#cli
  dev_url: https://github.com/vega/vega-lite

extra:
  recipe-maintainers:
    - johanneskoester
    - xhochy
