{% set name = "vega-lite-cli" %}
{% set version = "5.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vega/vega-lite/archive/refs/tags/v{{ version }}.tar.gz
  sha256: be00256bfbbc042e3d2185aefce54ffeca436caf952763a5df9dda49ae1c7dcc

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn <2
  run:
    - nodejs
    - vega-cli

test:
  commands:
    - curl -L https://github.com/vega/vega-lite/raw/v{{ version }}/examples/specs/bar.vl.json > test.json
    - vl2svg test.json > test.svg

about:
  home: https://vega.github.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Command line interface of the VEGA-lite visualization grammar
  description: |
    The vega-lite-cli package includes four node.js-based command line utilities -
    vl2pdf, vl2png, vl2svg, and vl2vg - for rendering static visualization images.
    These commands render to PDF, PNG, SVG files, or plain VEGA, respectively.
  doc_url: https://vega.github.io/vega-lite/usage/compile.html#cli
  dev_url: https://github.com/vega/vega-lite

extra:
  recipe-maintainers:
    - johanneskoester
    - xhochy
