travis:
  secure:
    BINSTAR_TOKEN: kxWusYwgEzFzQNVA/juZ8LHKtECUnEOd0+eiiEMmschdCDijXCnqg1hZzXNCFSL45cbIw5Aj4Eosf3kXvOZbUXGg+4dD85N/KCe5Octkycnolk2DVjpaaI354dG9gTamfG0flB+zbU16OUdgJ65VrG8qVxegDd1M+io2jdeg29N6NmuU0xBRVraSjRplWt1roDMOeFyeJZSW3ecOu45W43H82lXaebdxzMmKd9gmaVH4jQiGitLyH2BUuUVJbbeqm7S5fQ448Uk1ILq74GZvRRssNeBGOOKpcTmMDb1pTS47wsIKQ9kPhZuXEjouZCzY8nuwRd2LMwKU4aHdq/TXW5DSaxdGWBOEtthYnXVKpE12JQOZxTqfdokTiNUzoWpWgGsW7OURZhNTurg7eG7elSMg0/V9ZgKU8itrAB5YvMA5HRo53G9rPmyo6YEqPfgxVdR8cudcs94alp+vsAlZyiSSu77aKSlcN8FiBZYEylDPeMftjGRZjAmU/M2UYWhUsWTEgUgKpc6NS2KqQziC1vhoRXn4roMMx0X8ZG1ieuRnpYigX+nmhHiVxbqveIcASJPBlrJjsESnHgjHJUNEvtFuo4TsiMzsw75f4MHXR7uyWEEnEHeLMLW44TvL+1pCWcBIiCbyLeWHQmxxoqLxFrYIgXbq7MQo7eEDtX9CYns=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
